import type { Metadata } from "next";
import Providers from "@/components/providers";
import Footer from "@/components/footer";
import Nav from "@/components/nav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Personal website",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
};

const RootLayout = ({ children }: Readonly<RootLayoutProps>) => {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Nav />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
